package main.fb.suren.com.flybouncemain_v01.Models;

/**
 * Created by suren on 8/8/17.
 */

import com.j256.ormlite.field.DatabaseField;

import javax.persistence.Column;
import javax.persistence.Entity;

@Entity(name = "members")
public class Member {
    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    int id;

    @Column
    String _memberID;

    @Column
    String member_name;

    @Column
    String mobile_number;

    @Override
    public String toString() {
        return "Member{" +
                "id=" + id +
               ", _memberID='" + _memberID + '\'' +
                ", member_name='" + member_name + '\'' +
                ", mobile_number=" + mobile_number +
                '}';
    }

    public String get_memberID() {
        return _memberID;
    }

    public String getMember_name() {
        return member_name;
    }

    public String getMobile_number() {
        return mobile_number;
    }

    public Member() {
    }

    public Member(String _memberID, String member_name, String mobile_number) {
        this._memberID = _memberID;
        this.member_name = member_name;
        this.mobile_number = mobile_number;
    }
}
