package main.fb.suren.com.flybouncemain_v01.Models;

/**
 * Created by suren on 13/8/17.
 */

import com.j256.ormlite.field.DatabaseField;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;


@Entity(name = "payments")
public class Payments {



    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    int id;

    @Column(length = 50, nullable = false)
    String membership_ID;

    @DatabaseField
    Date payment_date;

    public Payments() {
    }

    public Payments(String membership_ID, Date payment_date) {
        this.membership_ID = membership_ID;
        this.payment_date = payment_date;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getMembership_ID() {
        return membership_ID;
    }

    public void setMembership_ID(String membership_ID) {
        this.membership_ID = membership_ID;
    }

    public Date getPayment_date() {
        return payment_date;
    }

    public void setPayment_date(Date payment_date) {
        this.payment_date = payment_date;
    }
}
