package main.fb.suren.com.flybouncemain_v01.database;

import com.j256.ormlite.field.DatabaseField;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;

import main.fb.suren.com.flybouncemain_v01.MainActivity;
import main.fb.suren.com.flybouncemain_v01.Utils;


/**
 * Created by suren on 17/7/17.
 */

@Entity(name = "members")
public class Member {

    Utils myUtils = new Utils();
    String targetDatePattern;

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    int id;

    @Column(length = 50,nullable = false)
    String member_name;

    @Column(length = 10,nullable = false)
    int mobile_number;

    @Column(length = 2,nullable = false)
    int startTime;

    @Column(length = 2, nullable = false)
    int courtNo;

    @DatabaseField
    Date startDate;

    @DatabaseField
    Date endDate;

    public Member(String member_name, int mobile_number, Date startDate, Date endDate, int startTime, int courtNo, String targetDatePattern) {

        this.targetDatePattern = targetDatePattern;
        this.member_name = member_name;
        this.mobile_number = mobile_number;
        this.startDate = startDate;
        this.endDate = endDate;
        this.startTime = startTime;
        this.courtNo = courtNo;
    }

    @Override
    public String toString() {
        return "Member{" +
                "myUtils=" + myUtils +
                ", targetDatePattern='" + targetDatePattern + '\'' +
                ", id=" + id +
                ", member_name='" + member_name + '\'' +
                ", mobile_number=" + mobile_number +
                ", startTime=" + startTime +
                ", startDate=" + startDate +
                ", endDate=" + endDate +
                '}';
    }

    public Member() {

    }
}
