package main.fb.suren.com.flybouncemain_v01.database;

/**
 * Created by suren on 8/8/17.
 */

import com.j256.ormlite.field.DatabaseField;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;

@Entity(name = "members")
public class Members {
    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    int id;

    @Column
    String member_id;

    @Column
    String member_name;

    @Column
    String mobile_number;

    @Override
    public String toString() {
        return "Members{" +
                "id=" + id +
                ", member_id='" + member_id + '\'' +
                ", member_name='" + member_name + '\'' +
                ", mobile_number=" + mobile_number +
                '}';
    }

    public String getMember_id() {
        return member_id;
    }

    public String getMember_name() {
        return member_name;
    }

    public String getMobile_number() {
        return mobile_number;
    }

    public Members() {
    }

    public Members(String member_id, String member_name, String mobile_number) {
        this.member_id = member_id;
        this.member_name = member_name;
        this.mobile_number = mobile_number;
    }
}
