package main.fb.suren.com.flybouncemain_v01.database;

import com.j256.ormlite.field.DatabaseField;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;


/**
 * Created by suren on 17/7/17.
 */

@Entity(name = "members")
public class Member {

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    int id;

    @Column(length = 50,nullable = false)
    String member_name;

    @Column(length = 10,nullable = false)
    int mobile_number;


    public Member(String member_name, int mobile_number) {

        this.member_name = member_name;
        this.mobile_number = mobile_number;
    }

    public Member() {

    }
}
