package main.fb.suren.com.flybouncemain_v01.database;

/**
 * Created by suren on 13/8/17.
 */

import com.j256.ormlite.field.DatabaseField;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;


@Entity(name = "payments")
public class Payments {



    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    int id;

    @Column(length = 50, nullable = false)
    String membership_ID;

    @DatabaseField
    Date payment_date;


}
